name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
    - name: Primeiro make
      run: make
    - name: make clean
      run: make clean
    - name: Segundo make
      run: make
    - name: make fclean
      run: make fclean
    - name: Terceiro make
      run: make
    - name: make lclean
      run: make lclean
    - name: make re
      run: make re
