name: Norminette

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  norme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Instalando dependencias
      run: |
        python -m pip install --upgrade pip
        pip install norminette
    - name: Testando Norma
      run: |
        norminette src
        norminette includes
